# Generated by Django 4.2.19 on 2025-04-16 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0002_alter_contact_iframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.IntegerField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contact.contact')),
            ],
        ),
    ]
