# Generated by Django 4.2.19 on 2025-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmessage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='center',
            field=models.CharField(max_length=200),
        ),
    ]
