# Generated by Django 4.2.19 on 2025-04-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_contact',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course_contact',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
