# Generated by Django 4.2.19 on 2025-04-19 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_activity_contact_is_paid_course_contact_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product', models.CharField(max_length=50)),
                ('product_title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('onOrderQty', models.IntegerField(default=0)),
                ('salesmen_id', models.IntegerField()),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product_contact',
            name='product',
            field=models.CharField(max_length=50),
        ),
    ]
