# Generated by Django 4.2.19 on 2025-04-20 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('contacts', '0003_takeorder_alter_product_contact_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_contact',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
        migrations.AlterField(
            model_name='takeorder',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
    ]
