# Generated by Django 4.2.19 on 2025-04-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_product_contact_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_contact',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='takeorder',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
