# Generated by Django 4.2.19 on 2025-04-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('products', '0001_initial'),
        ('courses', '0001_initial'),
        ('contacts', '0005_alter_product_contact_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_contact',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='course_contact',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='product_contact',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='takeorder',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='takeorder',
            name='product_title',
        ),
        migrations.AlterField(
            model_name='activity_contact',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='course_contact',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='product_contact',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='takeorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
