# Generated by Django 4.2.19 on 2025-04-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_activity_contact_activity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeorder',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
