# Generated by Django 4.2.19 on 2025-04-23 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_title'),
        ('activities', '0004_alter_activity_salesmen'),
        ('courses', '0003_remove_course_is_paid'),
        ('contacts', '0008_takeorder_ordered_alter_activity_contact_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_contact',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='course_contact',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='product_contact',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
        migrations.AlterField(
            model_name='takeorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
    ]
