# Generated by Django 4.2.19 on 2025-04-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobspost', '0001_initial'),
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='jobtitle',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='jobspost.jobs'),
        ),
    ]
