# Generated by Django 4.2.19 on 2025-04-17 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('detail', models.TextField()),
            ],
        ),
    ]
