# Generated by Django 4.2.19 on 2025-04-18 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0002_alter_newsevents_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsevents',
            name='content',
        ),
    ]
