# Generated by Django 4.2.19 on 2025-04-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0003_remove_newsevents_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevents',
            name='is_Events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='is_News',
            field=models.BooleanField(default=False),
        ),
    ]
