# Generated by Django 4.2.19 on 2025-04-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0004_newsevents_is_events_newsevents_is_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevents',
            name='iframe',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
