# Generated by Django 4.2.19 on 2025-04-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0005_newsevents_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
