# Generated by Django 4.2.19 on 2025-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField()),
                ('center', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('office_hours', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('iframe', models.CharField(max_length=200)),
            ],
        ),
    ]
