# Generated by Django 4.2.19 on 2025-04-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='iframe',
            field=models.CharField(max_length=600),
        ),
    ]
