# Generated by Django 4.2.19 on 2025-04-23 13:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0009_alter_activity_contact_activity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('address', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('district', models.CharField(choices=[('Islands', 'Islands'), ('Kwai Tsing', 'Kwai Tsing'), ('Sai Kung', 'Sai Kung'), ('Tsuen Wan', 'Tsuen Wan'), ('Tuen Mun', 'Tuen Mun'), ('Yuen Long', 'Yuen Long'), ('Wong Tai Sin', 'Wong Tai Sin'), ('Sha Tin', 'Sha Tin'), ('Tai Po', 'Tai Po'), ('Kowloon City', 'Kowloon City'), ('Kwun Tong', 'Kwun Tong'), ('Sham Shui Po', 'Sham Shui Po'), ('Yau Tsim Mong', 'Yau Tsim Mong'), ('Central & Western', 'Central & Western'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Wan Chai', 'Wan Chai'), ('North', 'North')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('total_Amount', models.IntegerField(default=0)),
                ('is_shipped', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ship_date', models.DateTimeField(default=datetime.datetime.now)),
                ('orders', models.ManyToManyField(to='contacts.takeorder')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
