# Generated by Django 4.2.19 on 2025-04-21 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_activity_contact_activity_id_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='no_1',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='no_3',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='no_4',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='no_5',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='no_6',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='onOrderQty_1',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='onOrderQty_2',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='onOrderQty_3',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='onOrderQty_4',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='onOrderQty_5',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='onOrderQty_6',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='price_1',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='price_3',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='price_4',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='price_5',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='price_6',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='salesmen',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='title_3',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='title_4',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='title_5',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='title_6',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='orders',
            field=models.ManyToManyField(to='contacts.takeorder'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='ship_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
