# Generated by Django 4.2.19 on 2025-04-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_shoppingcart_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='total_Amount',
            field=models.IntegerField(default=0),
        ),
    ]
