# Generated by Django 4.2.19 on 2025-04-21 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shoppingcart_is_completed_shoppingcart_is_shipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='ship_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
