# Generated by Django 4.2.19 on 2025-04-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportresources', '0002_remove_supportresources_sr_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportResources',
        ),
    ]
