# Generated by Django 4.2.19 on 2025-04-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportresources', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportResources',
        ),
    ]
