# Generated by Django 4.2.19 on 2025-04-22 02:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('srdetails', '0009_initial'),
        ('supportresources', '0009_delete_supportresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('web_url', models.URLField(blank=True, max_length=500)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sr_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='srdetails.srdetail')),
            ],
        ),
    ]
