# Generated by Django 4.2.19 on 2025-04-14 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salesmens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotitem', models.BooleanField(default=False)),
                ('title', models.CharField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('date_start', models.DateField(blank=True, default=datetime.datetime.now)),
                ('date_end', models.DateField(blank=True, default=datetime.datetime.now)),
                ('time_start', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('time_end', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('location', models.CharField(max_length=50)),
                ('medium', models.CharField(choices=[('Cantonese', 'Cantonese'), ('English', 'English'), ('Mandarin', 'Mandarin')], max_length=50)),
                ('target', models.CharField(max_length=200)),
                ('trainer', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('total_sit', models.IntegerField(default=0)),
                ('onenquiry_sit', models.IntegerField(default=0)),
                ('phaseOut', models.BooleanField(default=False)),
                ('salesmen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salesmens.salesmen')),
            ],
        ),
    ]
