# Generated by Django 4.2.19 on 2025-04-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_paid',
        ),
    ]
