# Generated by Django 4.2.19 on 2025-04-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmens', '0002_alter_salesmen_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmen',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
