# Generated by Django 4.2.19 on 2025-04-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportresources', '0002_remove_supportresources_sr_items'),
        ('srdetails', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Srdetails',
        ),
    ]
