# Generated by Django 4.2.19 on 2025-04-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('srdetails', '0002_delete_srdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Srdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemsname', models.CharField(max_length=200)),
                ('items_no', models.CharField(max_length=200)),
            ],
        ),
    ]
