# Generated by Django 4.2.19 on 2025-04-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportresources', '0005_delete_supportresources'),
        ('srdetails', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Srdetails',
        ),
    ]
