# Generated by Django 4.2.19 on 2025-04-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('srdetails', '0008_delete_srdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Srdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemsname', models.CharField(max_length=200)),
                ('items_no', models.CharField(max_length=200)),
            ],
        ),
    ]
