# Generated by Django 4.2.19 on 2025-04-09 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Temporary', 'Temporary')], max_length=20)),
                ('salary', models.IntegerField()),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('location', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('responsibilities', models.TextField()),
                ('requirement', models.TextField()),
                ('email', models.CharField(default='atkincheung@yahoo.com.hk', max_length=100)),
            ],
        ),
    ]
