# Generated by Django 4.2.19 on 2025-04-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobspost', '0002_alter_jobs_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(max_length=80),
        ),
    ]
