<<<<<<< HEAD
# Generated by Django 4.2.19 on 2025-04-12 06:39
=======
# Generated by Django 4.2.19 on 2025-04-14 14:05
>>>>>>> origin/WCNgApps

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salesmens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('photos', models.ImageField(upload_to='photos/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotitem', models.BooleanField(default=False)),
                ('no', models.CharField(max_length=50)),
                ('operation', models.CharField(choices=[('App', 'App'), ('PC', 'PC'), ('Point to Point', 'Point to Point')], max_length=50)),
                ('control', models.CharField(choices=[('PLC', 'PLC'), ('Mechanical', 'Mechanical'), ('Electronic', 'Electronic')], max_length=50)),
                ('automation', models.CharField(choices=[('Automatic', 'Automatic'), ('Semi-Automatic', 'Semi-Automatic'), ('None', 'None')], max_length=50)),
                ('application', models.CharField(choices=[('Pick and Place', 'Pick and Place'), ('Welding', 'Welding'), ('Automotive Ind.', 'Automotive Ind.'), ('Delivery', 'Delivery'), ('Cleaning', 'Cleaning'), ('Other', 'Other')], max_length=50)),
                ('power', models.CharField(choices=[('AC-220', 'AC-220'), ('AC-384', 'AC-384'), ('Battery', 'Battery')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('stockQty', models.IntegerField(default=0)),
                ('onOrderQty', models.IntegerField(default=0)),
                ('phaseOut', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('salesmen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salesmens.salesmen')),
                ('title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.category')),
            ],
        ),
    ]
